version: '3.1'
services:
  db:
    image: 'postgres:15.2-alpine'
    container_name: farmu_db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=db_farmu
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root